name: Require Approval Indicator
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
  pull_request_review:
    types: [submitted, edited, dismissed]

jobs:
  approval_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check for at least one approved review
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request?.number || context.issue.number;
            const reviews = await github.paginate(github.rest.pulls.listReviews, {
              owner, repo, pull_number: prNumber
            });
            const approved = reviews.some(r => r.state === 'APPROVED');
            core.setOutput('approved', approved ? 'true' : 'false');
            if (!approved) {
              core.setFailed('No approved review yet.');
            }
      - name: Summary
        if: always()
        run: |
          if [ "${{ steps.check.outputs.approved }}" = "true" ]; then
            echo "✅ At least one approval present."
          else
            echo "❌ No approvals yet."
          fi
